server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: test
    password: test
  jpa:
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    generate-ddl: true
    open-in-view: true
